<?php
print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "<head>\n";
print "<title>Schools</title>\n";
print "<meta charset=\"utf-8\">\n";
print "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "<meta name=\"description\" content=\"Course Project\">\n";
print "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap4/bootstrap.min.css\">\n";
print "<link href=\"plugins/fontawesome-free-5.0.1/css/fontawesome-all.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n";
print "</head>\n";
print "<body>\n";
print "\n";
print "<div class=\"super_container\">\n";
print "\n";
print "	<!-- Header -->\n";
print "\n";
print "	<header class=\"header d-flex flex-row\">\n";
print "		<div class=\"header_content d-flex flex-row align-items-center\">\n";
print "			<!-- Logo -->\n";
print "			<div class=\"logo_container\">\n";
print "				<div class=\"logo\">\n";
print "					<img src=\"images/logo.png\" alt=\"\">\n";
print "					<span>Schools</span>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "			<!-- Main Navigation -->\n";
print "			<nav class=\"main_nav_container\">\n";
print "				<div class=\"main_nav\">\n";
print "					<ul class=\"main_nav_list\">\n";
print "						<li class=\"main_nav_item\"><a href=\"index.html\">home</a></li>\n";
print "						<li class=\"main_nav_item\"><a href=\"#\">about us</a></li>\n";
print "						<li class=\"main_nav_item\"><a href=\"news.html\">news</a></li>\n";
print "						<li class=\"main_nav_item\"><a href=\"contact.html\">contact</a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "			</nav>\n";
print "		</div>\n";
print "		<div class=\"header_side d-flex flex-row justify-content-center align-items-center\">\n";
print "			<img src=\"images/phone-call.svg\" alt=\"\">\n";
print "			<span>+254790779806</span>\n";
print "		</div>\n";
print "\n";
print "		<!-- Hamburger -->\n";
print "		<div class=\"hamburger_container\">\n";
print "			<i class=\"fas fa-bars trans_200\"></i>\n";
print "		</div>\n";
print "\n";
print "	</header>\n";
print "	\n";
print "	\n";
print "	<!-- Menu -->\n";
print "	<div class=\"menu_container menu_mm\">\n";
print "\n";
print "		<!-- Menu Close Button -->\n";
print "		<div class=\"menu_close_container\">\n";
print "			<div class=\"menu_close\"></div>\n";
print "		</div>\n";
print "\n";
print "		<!-- Menu Items -->\n";
print "		<div class=\"menu_inner menu_mm\">\n";
print "			<div class=\"menu menu_mm\">\n";
print "				<ul class=\"menu_list menu_mm\">\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"#\">Home</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"#\">About us</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"courses.html\">Courses</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"elements.html\">Elements</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"news.html\">News</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"contact.html\">Contact</a></li>\n";
print "				</ul>\n";
print "\n";
print "				<!-- Menu Social -->\n";
print "				\n";
print "				<div class=\"menu_social_container menu_mm\">\n";
print "					<ul class=\"menu_social menu_mm\">\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-pinterest\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "\n";
print "				<div class=\"menu_copyright menu_mm\">Colorlib All rights reserved</div>\n";
print "			</div>\n";
print "\n";
print "		</div>\n";
print "\n";
print "	</div>\n";
print "	\n";
print "	<!-- Home -->\n";
print "\n";
print "	<div class=\"home\">\n";
print "\n";
print "		<!-- Hero Slider -->\n";
print "		<div class=\"hero_slider_container\">\n";
print "			<div class=\"hero_slider owl-carousel\">\n";
print "				\n";
print "				<!-- Hero Slide -->\n";
print "				<div class=\"hero_slide\">\n";
print "					<div class=\"hero_slide_background\" style=\"background-image:url(images/slider_background.jpg)\"></div>\n";
print "					<div class=\"hero_slide_container d-flex flex-column align-items-center justify-content-center\">\n";
print "						<div class=\"hero_slide_content text-center\">\n";
print "							<h1 data-animation-in=\"fadeInUp\" data-animation-out=\"animate-out fadeOut\">Find <span>Schools</span> easily</h1>\n";
print "						</div>\n";
print "					</div>\n";
print "				</div>\n";
print "				\n";
print "				<!-- Hero Slide -->\n";
print "				<div class=\"hero_slide\">\n";
print "					<div class=\"hero_slide_background\" style=\"background-image:url(images/slider_background.jpg)\"></div>\n";
print "					<div class=\"hero_slide_container d-flex flex-column align-items-center justify-content-center\">\n";
print "						<div class=\"hero_slide_content text-center\">\n";
print "							<h1 data-animation-in=\"fadeInUp\" data-animation-out=\"animate-out fadeOut\">Search <span>for</span>schools</h1>\n";
print "						</div>\n";
print "					</div>\n";
print "				</div>\n";
print "				\n";
print "				<!-- Hero Slide -->\n";
print "				<div class=\"hero_slide\">\n";
print "					<div class=\"hero_slide_background\" style=\"background-image:url(images/slider_background.jpg)\"></div>\n";
print "					<div class=\"hero_slide_container d-flex flex-column align-items-center justify-content-center\">\n";
print "						<div class=\"hero_slide_content text-center\">\n";
print "							<h1 data-animation-in=\"fadeInUp\" data-animation-out=\"animate-out fadeOut\">Find <span>education</span> events</h1>\n";
print "						</div>\n";
print "					</div>\n";
print "				</div>\n";
print "\n";
print "			</div>\n";
print "\n";
print "			<div class=\"hero_slider_left hero_slider_nav trans_200\"><span class=\"trans_200\">prev</span></div>\n";
print "			<div class=\"hero_slider_right hero_slider_nav trans_200\"><span class=\"trans_200\">next</span></div>\n";
print "		</div>\n";
print "\n";
print "	</div>\n";
print "\n";
print "\n";
print "\n";
print "				\n";
print "				<!-- School links -->\n";
print "				 <div class=\"links\">\n";
print "				<ul>\n";
print "				<li class=\"links\"><a href=\"#\">Agoro Sare Secondary School</a></li>\n";
print "				<li class=\"links\"><a href=\"http://alliancehighschool.sc.ke\">Alliance Boys High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Alliance Girls High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Banda school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Braeburn School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Brookhouse International School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Highway Secondary School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">International School of Kenya</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Kianda school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Lenana high school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Loreto Convent Msongaria</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Loreto Convent Valley Road</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Jamhuri High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Kagumo High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Kakamega High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Kisumu boys high school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Kisumu girls high school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Makini school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Mangu High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Maseno School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Moi Forces Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Moi Girls Eldoret</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Mombasa Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Mombasa Baptist</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Musingu high school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Nairobi School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Nakuru Boys High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Ngara girls high school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Nguviu Boys High School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Oshwal Academy Junior high</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Oshwal Academy Senior high</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Oshwal Academy Nairobi primary</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Rift Valley Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Rosslyn Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Saint Austins Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Sawagongo high school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Serare school</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Starehe Boys Centre</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">Strathmore School</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">St Mary's School Nairobi</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">St Marys Yala</a></li>\n";
print "				<li class=\"links\"><a href=\"#\">St Peters Mumias boys</a></li>\n";
print "\n";
print "\n";
print "				\n";
print "				</div>\n";
print "			</div>\n";
print "		</div>		\n";
print "	</div>\n";
print "\n";
print "	\n";
print "\n";
print "			<!-- Footer Content -->\n";
print "\n";
print "			<div class=\"footer_content\">\n";
print "				<div class=\"row\">\n";
print "\n";
print "					<!-- Footer Column - About -->\n";
print "					<div class=\"col-lg-3 footer_col\">\n";
print "\n";
print "						<!-- Logo -->\n";
print "						<div class=\"logo_container\">\n";
print "							<div class=\"logo\">\n";
print "								<img src=\"images/logo.png\" alt=\"\">\n";
print "								<span>course</span>\n";
print "							</div>\n";
print "						</div>\n";
print "\n";
print "						<p class=\"footer_about_text\">In aliquam, augue a gravida rutrum, ante nisl fermentum nulla, vitae tempor nisl ligula vel nunc. Proin quis mi malesuada, finibus tortor fermentum, tempor lacus.</p>\n";
print "\n";
print "					</div>\n";
print "\n";
print "					<!-- Footer Column - Menu -->\n";
print "\n";
print "					<div class=\"col-lg-3 footer_col\">\n";
print "						<div class=\"footer_column_title\">Menu</div>\n";
print "						<div class=\"footer_column_content\">\n";
print "							<ul>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">Home</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">About Us</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"courses.html\">Courses</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"news.html\">News</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"contact.html\">Contact</a></li>\n";
print "							</ul>\n";
print "						</div>\n";
print "					</div>\n";
print "\n";
print "					<!-- Footer Column - Usefull Links -->\n";
print "\n";
print "					<div class=\"col-lg-3 footer_col\">\n";
print "						<div class=\"footer_column_title\">Usefull Links</div>\n";
print "						<div class=\"footer_column_content\">\n";
print "							<ul>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">Testimonials</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">FAQ</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">Community</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">Campus Pictures</a></li>\n";
print "								<li class=\"footer_list_item\"><a href=\"#\">Tuitions</a></li>\n";
print "							</ul>\n";
print "						</div>\n";
print "					</div>\n";
print "\n";
print "					<!-- Footer Column - Contact -->\n";
print "\n";
print "					<div class=\"col-lg-3 footer_col\">\n";
print "						<div class=\"footer_column_title\">Contact</div>\n";
print "						<div class=\"footer_column_content\">\n";
print "							<ul>\n";
print "								<li class=\"footer_contact_item\">\n";
print "									<div class=\"footer_contact_icon\">\n";
print "										<img src=\"images/placeholder.svg\" alt=\"https://www.flaticon.com/authors/lucy-g\">\n";
print "									</div>\n";
print "									Blvd Libertad, 34 m05200 Arévalo\n";
print "								</li>\n";
print "								<li class=\"footer_contact_item\">\n";
print "									<div class=\"footer_contact_icon\">\n";
print "										<img src=\"images/smartphone.svg\" alt=\"https://www.flaticon.com/authors/lucy-g\">\n";
print "									</div>\n";
print "									0034 37483 2445 322\n";
print "								</li>\n";
print "								<li class=\"footer_contact_item\">\n";
print "									<div class=\"footer_contact_icon\">\n";
print "										<img src=\"images/envelope.svg\" alt=\"https://www.flaticon.com/authors/lucy-g\">\n";
print "									</div>hello@company.com\n";
print "								</li>\n";
print "							</ul>\n";
print "						</div>\n";
print "					</div>\n";
print "\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "			<!-- Footer Copyright -->\n";
print "\n";
print "			<div class=\"footer_bar d-flex flex-column flex-sm-row align-items-center\">\n";
print "				\n";
print "				<div class=\"footer_social ml-sm-auto\">\n";
print "					<ul class=\"menu_social\">\n";
print "						<li class=\"menu_social_item\"><a href=\"#\"><i class=\"fab fa-pinterest\"></i></a></li>\n";
print "						<li class=\"menu_social_item\"><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n";
print "						<li class=\"menu_social_item\"><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n";
print "						<li class=\"menu_social_item\"><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\n";
print "						<li class=\"menu_social_item\"><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "		</div>\n";
print "	</footer>\n";
print "\n";
print "</div>\n";
print "\n";
print "<script src=\"js/jquery-3.2.1.min.js\"></script>\n";
print "<script src=\"styles/bootstrap4/popper.js\"></script>\n";
print "<script src=\"styles/bootstrap4/bootstrap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n";
print "<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n";
print "<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n";
print "<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n";
print "<script src=\"plugins/scrollTo/jquery.scrollTo.min.js\"></script>\n";
print "<script src=\"plugins/easing/easing.js\"></script>\n";
print "<script src=\"js/custom.js\"></script>\n";
print "\n";
print "</body>\n";
print "</html>";
?>
