<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "<head>\n";
print "<title>Primary Schools</title>\n";
print "<meta charset=\"utf-8\">\n";
print "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "<meta name=\"description\" content=\"Course Project\">\n";
print "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap4/bootstrap.min.css\">\n";
print "<link href=\"plugins/fontawesome-free-5.0.1/css/fontawesome-all.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n";
print "</head>\n";
print "<body>\n";
print "\n";
print "<div class=\"super_container\">\n";
print "\n";
print "	<!-- Header -->\n";
print "\n";
print "	<header class=\"header d-flex flex-row\">\n";
print "		<div class=\"header_content d-flex flex-row align-items-center\">\n";
print "			<!-- Logo -->\n";
print "			<div class=\"logo_container\">\n";
print "				<div class=\"logo\">\n";
print "					<img src=\"images/logo.png\" alt=\"\">\n";
print "					<span>Primary Schools</span>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "			<!-- Main Navigation -->\n";
print "			<nav class=\"main_nav_container\">\n";
print "				<div class=\"main_nav\">\n";
print "					<ul class=\"main_nav_list\">\n";
print "						<li class=\"main_nav_item\"><a href=\"index.php\">home</a></li>\n";
print "						<li class=\"main_nav_item\"><a href=\"schools.php\">schools</a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "			</nav>\n";
print "		</div>\n";
print "		<div class=\"header_side d-flex flex-row justify-content-center align-items-center\">\n";
print "			<img src=\"images/phone-call.svg\" alt=\"\">\n";
print "			<span>+254790779806</span>\n";
print "		</div>\n";
print "\n";
print "		<!-- Hamburger -->\n";
print "		<div class=\"hamburger_container\">\n";
print "			<i class=\"fas fa-bars trans_200\"></i>\n";
print "		</div>\n";
print "\n";
print "	</header>\n";
print "	\n";
print "	\n";
print "	<!-- Menu -->\n";
print "	<div class=\"menu_container menu_mm\">\n";
print "\n";
print "		<!-- Menu Close Button -->\n";
print "		<div class=\"menu_close_container\">\n";
print "			<div class=\"menu_close\"></div>\n";
print "		</div>\n";
print "\n";
print "		<!-- Menu Items -->\n";
print "		<div class=\"menu_inner menu_mm\">\n";
print "			<div class=\"menu menu_mm\">\n";
print "				<ul class=\"menu_list menu_mm\">\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"#\">Home</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"courses.html\">Courses</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"elements.html\">Elements</a></li>\n";
print "				</ul>\n";
print "\n";
print "				<!-- Menu Social -->\n";
print "				\n";
print "				<div class=\"menu_social_container menu_mm\">\n";
print "					<ul class=\"menu_social menu_mm\">\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-pinterest\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "\n";
print "				<div class=\"menu_copyright menu_mm\">Colorlib All rights reserved</div>\n";
print "			</div>\n";
print "\n";
print "		</div>\n";
print "\n";
print "	</div>\n";
print "	\n";
print 
print "	<!-- Popular -->\n";
print "\n";
print "	<div class=\"popular page_section\">\n";
print "		<div class=\"container\">\n";
print "			<div class=\"row\">\n";
print "				<div class=\"col\">\n";
print "					<div class=\"section_title text-center\">\n";
print "						<h1>Primary Schools</h1>\n";
print "					</div>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "				<!-- School links -->\n";
print "				 <div class=\"links\">\n";
print "				<ul>\n";
print "				<li class=\"links\"><a href=\"https://www.alkhairiaintergrated.sc.ke\">Al Khairia Integrated Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.alfahacademy.com\">Alfah Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.aligulaprimary.sc.ke\">Aligula Primary School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.allsaintskianyaga.sc.ke\">Allsaints Kianyaga Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.alomodoiprimary.sc.ke\">Alomodoi Primary School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.amukeniprimary.sc.ke\">Amukeni Primary School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.angenoprimary.sc.ke\">Angeno Primary School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://anindoprimary.sc.ke\">Anindo Primary School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.apegeiprimary.sc.ke\"> Apegei Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.arimiprimary.sc.ke\"> Arimi Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://btgachievers.sc.ke\"> Back To Glory Achievers School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.baharipreparatory.com\"> Bahari Preparatory </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bahatinorthacademy.sc.ke\"> Bahati North Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.balozijunior.sc.ke\"> Balozi Junior Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bamburignadventist.sc.ke\"> Bamburi Good News Adventist Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bamburijunior.sc.ke \"> Bamburi Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://bandaschool.com\">Banda School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://baraguluprimary.sc.ke\"> Bar Agulu Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.barakaprimary.sc.ke\"> Baraka Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.barshebacentralacademy.com\"> Barisheba Central Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bettervisionschool.sc.ke\"> Better Vision School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bidiiprimary.ac.ke\"> Bidii Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bomuprimaryschool.com\"> Bomu Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bondenigirlsprimary.com\"> Bondeni Girls Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bondeniprimary.sc.ke\"> Bondeni Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bondodeo.or.ke\"> Bondo D.E.O </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.boonhouseschool.com\"> Boonhouse School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://braeburn.com\">Braeburn School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bridgeofhopeacademy.sc.ke\"> Bridge Of Hope Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bridgewoodschool.com\"> Bridgewood School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.brightdestiny.sc.ke\"> Bright Destiny Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.brightjunior.sc.ke\"> Bright Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://brookhouse.ac.ke\">Brookhouse School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chrispreparatory.sc.ke\"> Chris Preparatory School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.coraljuniorschool.sc.ke\"> Coral Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.craterprimary.sc.ke\"> Crater Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.dekkoacademy.sc.ke\"> Dekko Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.denrowjunior.sc.ke\"> Denrow Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.destinygardenschool.com\"> Destiny Garden School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.diplomatcommunityeducationcentre.sc.ke\"> Diplomat Community Ed. Centre </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.dundoriprimary.sc.ke\"> Dundori Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.edelvaleprimary.sc.ke\"> Edelvale Primary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.engoshuraprimary.sc.ke\"> Engoshura Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://etonschoolkenya\">Eton School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.everbrightdigitalacademy.sc.ke\"> Everbright Digital Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://fahariprimary.sc.ke\"> Fahari Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.floristacademy.sc.ke\"> Florist Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.fortjesusacademy.com\"> Fort Jesus Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.freretownprimary.sc.ke\"> Frere Town Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.friendspointacademy.sc.ke\"> Friends Point Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.furahajunior.sc.ke\"> Furaha Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.furahaprimary.sc.ke\"> Furaha Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ganjoni.com\"> Ganjoni Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gatangagirlsbrown.sc.ke\"> Gatanga Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gatuguraprimary.sc.ke\"> Gatugura Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gatweprimary.sc.ke\"> Gatwe Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gccmjunior.sc.ke\"> Gccm Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gilgilgarrisonprimary.sc.ke\"> Gilgil Garrison Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gotkacholaprimary.com\"> Got Kachola Primary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.greatnileacademy.sc.ke\"> Great Nile Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.greenpalmsacademy.sc.ke\"> Green Palms Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.harvestprimary.sc.ke\"> Harvest Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.havilahschool.sc.ke\"> Havilah School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.hyraxprimary.sc.ke\"> Hyrax Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.islandviewacademy.sc.ke\"> Island View Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jmkariukimemorial.sc.ke\"> J. M. Kariuki Memorial </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jamhuriprimary.sc.ke\"> Jamhuri Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jitihadaschool.com\"> Jitihada Communintyschool </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.josnahschool.sc.ke\"> Josnah Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jufredprimary.com\"> Jufred Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kabatipottershouse.sc.ke\"> Kabati Potterhouse Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://kabongoiprimary.sc.ke\"> Kabongoi Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kaburaulwanfm.sc.ke\"> Kabura Ulwan F.M. Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kadikaprimary.sc.ke\"> Kadika Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kagumoccmprimary.sc.ke\"> Kagumo CCM Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kambouprimary.sc.ke\"> Kambou Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kamuiruprimary.sc.ke\"> Kamuiru Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.karainiprimary.sc.ke\"> Karaini Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwailuprimary.sc.ke\"> Kari Mwailu Boarding Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kasingeprimary.sc.ke\"> Kasinge Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kayolenorthprimary.sc.ke\"> Kayole North Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kayoleprimary.sc.ke\"> Kayole Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.khadijaprimary.sc.ke\"> Khadija Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kholeraprimary.sc.ke\"> Kholera Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamainaprimaryschool.sc.ke\"> Kiamaina Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamutuiraprimary.sc.ke\"> Kiamutuira Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://kiandaschool.ac.ke\">Kianda School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kibathiprimary.sc.ke\"> Kibathi Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kibuthaboardingpri.sc.ke\"> Kibutha Boarding Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiembenieliteprimary.sc.ke\"> Kiembeni Elite Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kifaruprimary.sc.ke\"> Kifaru Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiganjoprimary.sc.ke\"> Kiganjo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kihumbuprimary.sc.ke\"> Kihumbu Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kilimanjaropremier.sc.ke\"> Kilimanjaro Premier Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kingspreparatory.sc.ke\"> Kings Preparatory </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kirigoprimary.sc.ke\"> Kirigo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiriikomakinischool.com\"> Kiriiko Makini Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisauniprimary.sc.ke\"> Kisauni Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisauniprimary.com\"> Kisauni Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisumuunionprimary.sc.ke\"> Kisumu Union Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.komarockprimary.sc.ke\"> Komarock Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kwamejunior.sc.ke\"> Kwame Junior Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kwanjengaprimary.sc.ke\"> Kwa Njenga Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lightraysacademy.sc.ke\"> Lightrays Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.littlestaracademy.com\"> Little Star Academy -Maweni </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.longoprimary.sc.ke\"> Longo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.luoraprimary.sc.ke\"> Luora Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mopeducatonalcentre.sc.ke\"> M.O.P Educational Centre </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.machakosacademy.com\"> Machakos Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.maginaprimary.sc.ke\"> Magina Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.makandeprimary.com\"> Makande Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://makinischools.ac.ke\">Makini Schools</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.maleraprimary.sc.ke\"> Malera Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mamanginaprimary.sc.ke\"> Mama Ngina Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.maperaprimary.com\"> Mapera Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mariakaniprimary.sc.ke\"> Mariakani Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mariannagloriousacademy.sc.ke\"> Marianna Glorious Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.marveljunioracademy.com\"> Marvel Junior Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.masenogirls.com\"> Maseno Girls Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://matagalaprimary.sc.ke\"> Matagala Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mauaprimary.sc.ke\"> Maua Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.menengaiprimary.sc.ke\"> Menengai Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.micansacademy.com\"> Micans Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.migoriprimary.com\"> Migori Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mihangoprimary.sc.ke\"> Mihango Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.milimaniprimary.com\"> Milimani Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mnazimojaprimary.sc.ke\"> Mnazi Moja Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moiavenue.ac.ke\"> Moi Avenue Primary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mombasaprimary.com\"> Mombasa Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mtsinaiacademy.com\"> Mt. Sinai Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mteverestacademy.com\"> Mt.Everest Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mtongweprimary.sc.ke\"> Mtongwe Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mtwapabrightacademy.sc.ke\"> Mtwapa Bright Academy </a></li>\n";	
print "				<li class=\"links\"><a href=\"https://www.mugumoprimary.sc.ke\"> Mugumo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.muhoronideo.or.ke\"> Muhoroni D.E.O </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mvitaprimary.com\">Mvita Primary School  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nairobisouthprimary.sc.ke\"> Nairobi South Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nakurueastprimary.sc.ke\"> Nakuru East Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nakuruteachersprimary.sc.ke\"> Nakuru Teachers Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nakuruworkersprimary.sc.ke\"> Nakuru Workers Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://namgoiprimary.sc.ke\"> Namgoi Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.newmoonprimary.sc.ke\"> New Moon Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ngenyprimary.sc.ke\"> Ng’eny Intergrated Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.njorodebprimary.sc.ke\"> Njoro Deb Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyaberaprimary.sc.ke\"> Nyabera Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyakachmixed.sc.ke\"> Nyakach Mixed Primary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyakokoprimary.sc.ke\"> Nyakoko Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyamarimbapry.sc.ke\"> Nyamarimba Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyambecheprimary.sc.ke\"> Nyambeche Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nysgilgilprimary.sc.ke\"> NYS Gilgil Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.oceanicgreenfieldacademy.sc.ke\"> Oceanic Greenfield Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.oduwoprimary.sc.ke\"> Oduwo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ongecheschool.sc.ke\"> Ong’eche Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pceaelburgonprimary.sc.ke\"> PCEA Elburgon Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pceamakupaacademy.com\"> PCEA Makupa Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pearlsworthschool.com\"> Pearlsworth Preparatoryschool </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.peterkibukosyaprimary.sc.ke\"> Peter Kibukoya Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.plainsviewprimary.sc.ke\"> Plainsview Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kabatipottersacademy.ac.ke\"> Potter’s Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pwanijunioracademy.sc.ke\"> Pwani Junior Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pwanispecialschool.com\"> Pwani Special School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.rasulalakram.com\"> Rasul–Al–Akram Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.revmuhorosfd.com\"> Rev. Muhoro School For The Deaf </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.risenshineacademy.ac.ke\"> Rise And Shine Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.rgngalaprimary.com\"> Ronald G Ngala Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sacredheartprimaryschool.sc.ke\"> Sacred Heart Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.seasideacademy.sc.ke\"> Seaside Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://segutonprimary.sc.ke\"> Seguton Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.seregeyaprimary.sc.ke\"> Seregeya Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sheikhnurein.com\"> Sheikh Zurein Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://sibangaprimary.sc.ke\"> Sibanga Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sinenoeducationcentre.com\"> Sineno Education Centre </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.skyviewskul.com\"> Skyview Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sonysugarprimary.sc.ke\"> Sony Sugar Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://sotitprimary.sc.ke\"> Sotit Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.assarjohansonpri.com\"> Ssar Johanson Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://staustins.ac.ke\">St. Austin's Academy</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stcatherinesacademy.ac.ke\"> St. Cathrines Mountainview Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stdennisnyaliacademy.sc.ke\"> St. Dennis Nyali Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stelizabethintegrated.org\"> St. Elizabeth Integrated Junior Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stelizabethschools.sc.ke\"> St. Elizabeth Schools </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjohnsoriang.sc.ke\"> St. John Oriang’ Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjohnsprimary.sc.ke\"> St. Johns Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.judejuniorschool.com\"> St. Jude Junior School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stkevinbombolulu.sc.ke\"> St. Kevin Bombolulu Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stmichaelgirlsprimary.sc.ke\"> St. Michael Girls Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stpeterstherock.com\"> St. Peter The Rock </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stpetersbpmumias.com\"> St. Peters Boys Primary – Mumias </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stpetersboysprimary.sc.ke\"> St. Peters Boys Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stfrancismajengoprimary.sc.ke\"> St.Francics Majengo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stlukesschoolfordeaf.sc.ke\"> St.Lukes Special School For The Deaf </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.starshineacademy.sc.ke\"> Star Shine Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://suboprimary.sc.ke\"> Subo Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thawabuprimary.sc.ke\"> Thawabu Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.marionschools.ac.ke\"> The Marion Schools </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thimbiguaprimary.sc.ke\"> Thimbigua Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tiwiredeemedacad.sc.ke\"> Tiwi Redeemed Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tommboyaraganaprimary.sc.ke\"> Tom Mboya Ragana Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tmboyacp.com\"> Tom Mboya School For The Cerebral Palsy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.treesidespecialschool.sc.ke\"> Treeside Special School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tudorprimaryschool.com\"> Tudor Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tudorspecialschool.com\"> Tudor Special School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tumainihouse.sc.ke\"> Tumaini House School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tumainiprimary.sc.ke\"> Tumaini Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.tuthuprimary.sc.ke\"> Tuthu Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.uhurugardensprimary.sc.ke\"> Uhuru Gardens Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.unityprimary.sc.ke\"> Unity Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.victoryeducationcentre.sc.ke\"> Victory Education Centre </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.wankanacademy.sc.ke\"> Wankan Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.welldoneacademy.sc.ke\"> Well Done Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ziwaniprimary.com\"> Ziwani Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ziwanischool.com\"> Ziwani School For The Deaf </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://\">  </a></li>\n";





print "\n";
print "\n";
print "				\n";
print "				</div>\n";
print "		</div>		\n";
print "	</div>\n";
print "\n";
print "	<!-- Register -->\n";
print "\n";
print "	<div class=\"register\">\n";
print "\n";
print "		<div class=\"container-fluid\">\n";
print "			\n";
print "			<div class=\"row row-eq-height\">\n";
print "				\n";
print "\n";
print "				<div class=\"col-lg-6 nopadding\">\n";
print "					\n";
print "					<!-- Search -->\n";
;
print "\n";
print "				</div>\n";
print "			</div>\n";
print "		</div>\n";
print "	</div>\n";
print "\n";
print "	<!-- Services -->\n";
print "\n";
print "	<div class=\"services page_section\">\n";
print "		\n";
print "\n";
print "	</div>\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "</div>\n";
print "\n";
print "<script src=\"js/jquery-3.2.1.min.js\"></script>\n";
print "<script src=\"styles/bootstrap4/popper.js\"></script>\n";
print "<script src=\"styles/bootstrap4/bootstrap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n";
print "<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n";
print "<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n";
print "<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n";
print "<script src=\"plugins/scrollTo/jquery.scrollTo.min.js\"></script>\n";
print "<script src=\"plugins/easing/easing.js\"></script>\n";
print "<script src=\"js/custom.js\"></script>\n";
print "\n";
print "</body>\n";
print "</html>";

?>
