<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "<head>\n";
print "<title>Schools</title>\n";
print "<meta charset=\"utf-8\">\n";
print "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "<meta name=\"description\" content=\"Course Project\">\n";
print "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap4/bootstrap.min.css\">\n";
print "<link href=\"plugins/fontawesome-free-5.0.1/css/fontawesome-all.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n";
print "</head>\n";
print "<body>\n";
print "\n";
print "<div class=\"super_container\">\n";
print "\n";
print "	<!-- Header -->\n";
print "\n";
print "	<header class=\"header d-flex flex-row\">\n";
print "		<div class=\"header_content d-flex flex-row align-items-center\">\n";
print "			<!-- Logo -->\n";
print "			<div class=\"logo_container\">\n";
print "				<div class=\"logo\">\n";
print "					<img src=\"images/logo.png\" alt=\"\">\n";
print "					<span>Schools</span>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "			<!-- Main Navigation -->\n";
print "			<nav class=\"main_nav_container\">\n";
print "				<div class=\"main_nav\">\n";
print "					<ul class=\"main_nav_list\">\n";
print "						<li class=\"main_nav_item\"><a href=\"index.php\">home</a></li>\n";
print "						<li class=\"main_nav_item\"><a href=\"schools.php\">schools</a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "			</nav>\n";
print "		</div>\n";
print "		<div class=\"header_side d-flex flex-row justify-content-center align-items-center\">\n";
print "			<img src=\"images/phone-call.svg\" alt=\"\">\n";
print "			<span>+254790779806</span>\n";
print "		</div>\n";
print "\n";
print "		<!-- Hamburger -->\n";
print "		<div class=\"hamburger_container\">\n";
print "			<i class=\"fas fa-bars trans_200\"></i>\n";
print "		</div>\n";
print "\n";
print "	</header>\n";
print "	\n";
print "	\n";
print "	<!-- Menu -->\n";
print "	<div class=\"menu_container menu_mm\">\n";
print "\n";
print "		<!-- Menu Close Button -->\n";
print "		<div class=\"menu_close_container\">\n";
print "			<div class=\"menu_close\"></div>\n";
print "		</div>\n";
print "\n";
print "		<!-- Menu Items -->\n";
print "		<div class=\"menu_inner menu_mm\">\n";
print "			<div class=\"menu menu_mm\">\n";
print "				<ul class=\"menu_list menu_mm\">\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"#\">Home</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"courses.html\">Courses</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"elements.html\">Elements</a></li>\n";
print "				</ul>\n";
print "\n";
print "				<!-- Menu Social -->\n";
print "				\n";
print "				<div class=\"menu_social_container menu_mm\">\n";
print "					<ul class=\"menu_social menu_mm\">\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-pinterest\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "\n";
print "				<div class=\"menu_copyright menu_mm\">Colorlib All rights reserved</div>\n";
print "			</div>\n";
print "\n";
print "		</div>\n";
print "\n";
print "	</div>\n";
print "	\n";
print 
print "	<!-- Popular -->\n";
print "\n";
print "	<div class=\"popular page_section\">\n";
print "		<div class=\"container\">\n";
print "			<div class=\"row\">\n";
print "				<div class=\"col\">\n";
print "					<div class=\"section_title text-center\">\n";
print "						<h1>Find Schools Websites</h1>\n";
print "					</div>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "			<div class=\"row course_boxes\">\n";
print "				\n";
print "				<!-- Popular Course Item -->\n";
print "				<div class=\"col-lg-4 course_box\">\n";
print "					<div class=\"card\">\n";
print "						<img class=\"card-img-top\" src=\"images/alliance.jpg\" alt=\"https://unsplash.com/@kellybrito\">\n";
print "						<div class=\"card-body text-center\">\n";
print "							<div class=\"card-title\"><a href=\"primaryschools.php\">Primary Schools</div>\n";
print "							\n";
print "						</div>\n";
print "					\n";
print "						\n";
print "					</div>\n";
print "				</div>\n";
print "\n";
print "\n";
print "				<!-- Popular Course Item -->\n";
print "				<div class=\"col-lg-4 course_box\">\n";
print "					<div class=\"card\">\n";
print "						<img class=\"card-img-top\" src=\"images/strathmore.jpg\" alt=\"https://unsplash.com/@dsmacinnes\">\n";
print "						<div class=\"card-body text-center\">\n";
print "							<div class=\"card-title\"><a href=\"secondaryschools.php\">Secondary Schools</a></div>\n";
print "						</div>\n";
print "						\n";
print "					</div>\n";
print "				</div>\n";
print "				\n";
print "				\n";
print "				<!-- School links -->\n";
print "			</div>\n";
print "		</div>		\n";


print "		<div>		\n";







print "		</div>		\n";


print "	</div>\n";
print "\n";
print "	<!-- Register -->\n";
print "\n";
print "	<div class=\"register\">\n";
print "\n";
print "		<div class=\"container-fluid\">\n";
print "			\n";
print "			<div class=\"row row-eq-height\">\n";
print "				\n";
print "\n";
print "				<div class=\"col-lg-6 nopadding\">\n";
print "					\n";
print "					<!-- Search -->\n";
;
print "\n";
print "				</div>\n";
print "			</div>\n";
print "		</div>\n";
print "	</div>\n";
print "\n";
print "	<!-- Services -->\n";
print "\n";
print "	<div class=\"services page_section\">\n";
print "		\n";
print "\n";
print "	</div>\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "</div>\n";
print "\n";
print "<script src=\"js/jquery-3.2.1.min.js\"></script>\n";
print "<script src=\"styles/bootstrap4/popper.js\"></script>\n";
print "<script src=\"styles/bootstrap4/bootstrap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n";
print "<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n";
print "<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n";
print "<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n";
print "<script src=\"plugins/scrollTo/jquery.scrollTo.min.js\"></script>\n";
print "<script src=\"plugins/easing/easing.js\"></script>\n";
print "<script src=\"js/custom.js\"></script>\n";
print "\n";
print "</body>\n";
print "</html>";

?>
