<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "<head>\n";
print "<title>Secondary Schools</title>\n";
print "<meta charset=\"utf-8\">\n";
print "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "<meta name=\"description\" content=\"Course Project\">\n";
print "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/bootstrap4/bootstrap.min.css\">\n";
print "<link href=\"plugins/fontawesome-free-5.0.1/css/fontawesome-all.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"plugins/OwlCarousel2-2.2.1/animate.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/main_styles.css\">\n";
print "<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/responsive.css\">\n";
print "</head>\n";
print "<body>\n";
print "\n";
print "<div class=\"super_container\">\n";
print "\n";
print "	<!-- Header -->\n";
print "\n";
print "	<header class=\"header d-flex flex-row\">\n";
print "		<div class=\"header_content d-flex flex-row align-items-center\">\n";
print "			<!-- Logo -->\n";
print "			<div class=\"logo_container\">\n";
print "				<div class=\"logo\">\n";
print "					<img src=\"images/logo.png\" alt=\"\">\n";
print "					<span>Secondary Schools</span>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "			<!-- Main Navigation -->\n";
print "			<nav class=\"main_nav_container\">\n";
print "				<div class=\"main_nav\">\n";
print "					<ul class=\"main_nav_list\">\n";
print "						<li class=\"main_nav_item\"><a href=\"index.php\">home</a></li>\n";
print "						<li class=\"main_nav_item\"><a href=\"schools.php\">schools</a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "			</nav>\n";
print "		</div>\n";
print "		<div class=\"header_side d-flex flex-row justify-content-center align-items-center\">\n";
print "			<img src=\"images/phone-call.svg\" alt=\"\">\n";
print "			<span>+254790779806</span>\n";
print "		</div>\n";
print "\n";
print "		<!-- Hamburger -->\n";
print "		<div class=\"hamburger_container\">\n";
print "			<i class=\"fas fa-bars trans_200\"></i>\n";
print "		</div>\n";
print "\n";
print "	</header>\n";
print "	\n";
print "	\n";
print "	<!-- Menu -->\n";
print "	<div class=\"menu_container menu_mm\">\n";
print "\n";
print "		<!-- Menu Close Button -->\n";
print "		<div class=\"menu_close_container\">\n";
print "			<div class=\"menu_close\"></div>\n";
print "		</div>\n";
print "\n";
print "		<!-- Menu Items -->\n";
print "		<div class=\"menu_inner menu_mm\">\n";
print "			<div class=\"menu menu_mm\">\n";
print "				<ul class=\"menu_list menu_mm\">\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"#\">Home</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"courses.html\">Courses</a></li>\n";
print "					<li class=\"menu_item menu_mm\"><a href=\"elements.html\">Elements</a></li>\n";
print "				</ul>\n";
print "\n";
print "				<!-- Menu Social -->\n";
print "				\n";
print "				<div class=\"menu_social_container menu_mm\">\n";
print "					<ul class=\"menu_social menu_mm\">\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-pinterest\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\n";
print "						<li class=\"menu_social_item menu_mm\"><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n";
print "					</ul>\n";
print "				</div>\n";
print "\n";
print "				<div class=\"menu_copyright menu_mm\">Colorlib All rights reserved</div>\n";
print "			</div>\n";
print "\n";
print "		</div>\n";
print "\n";
print "	</div>\n";
print "	\n";
print 
print "	<!-- Popular -->\n";
print "\n";
print "	<div class=\"popular page_section\">\n";
print "		<div class=\"container\">\n";
print "			<div class=\"row\">\n";
print "				<div class=\"col\">\n";
print "					<div class=\"section_title text-center\">\n";
print "						<h1>Secondary Schools</h1>\n";
print "					</div>\n";
print "				</div>\n";
print "			</div>\n";
print "\n";
print "		</div>		\n";
print "	</div>\n";
print "\n";
print "	<!-- Register -->\n";
print "\n";
print "	<div class=\"register\">\n";
print "\n";
print "		<div class=\"container-fluid\">\n";
print "			\n";
print "			<div class=\"row row-eq-height\">\n";
print "				\n";
print "\n";
print "				<div class=\"col-lg-6 nopadding\">\n";
print "					\n";
print "					<!-- Search -->\n";
;
print "\n";
print "				</div>\n";
print "			</div>\n";
print "		</div>\n";
print "	</div>\n";
print "\n";
print "				<!-- School links -->\n";
print "				 <div class=\"links\">\n";
print "				<ul>\n";
print "				<li class=\"links\"><a href=\"http://www.abothuguchihigh.sc.ke\">Abothuguchi Boys High School</a></li>\n";
print "				<li class=\"links\"><a href=\"http://www.afrahahigh.sc.ke\">Afraha High School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.aicisaackosgei.sc.ke\">AIC Isaac Kosgei Secondary School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moihighkaplamai.sc.ke\">AIC Moi High School Kaplamai</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.aicolkalousecondary.sc.ke\">AIC Ol-Kalou Secondary School</a></li>\n";
print "				<li class=\"links\"><a href=\"http://alliancehighschool.sc.ke\">Alliance Boys High School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.alliancegirlshigh.sc.ke\">Alliance Girls High School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.aquinashigh.sc.ke\"> Aquinas High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.asumbigirlshigh.sc.ke\"> Asumbi Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.baharigirls.com\"> Bahari Girls Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bandegirls.sc.ke \"> Bande Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.barakahigh.sc.ke\"> Baraka High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bgngandugirlshigh.sc.ke\"> Bishop Gatimu Ngandu Girls </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.bishopokindahigh.sc.ke\"> Bishop Okinda High School </a></li>\n";
print "				<li class=\"links\"><a href=\"http://braeburn.com\">Braeburn School</a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.buragirlsschool.com\"> Bura Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.buruburugirls.com\"> Buruburu Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.canonnjumbisecondary.sc.ke\"> Canon Njumbi Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.cardinalotungagirls.sc.ke\"> Cardinal Otunga Girls </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chaniagirlshigh.sc.ke\"> Chania Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chapunguprimary.sc.ke\"> Chapungu Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chawiaschool.sc.ke\"> Chawia High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.cheborgehigh.sc.ke\"> Cheborge  High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://chemoibensecondary.sc.ke\"> Chemoiben Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.cheptaisboyshigh.sc.ke\"> Chepatais Boys High </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chingaboys.org\"> Chinga Boys High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chulaimboboyssec.com\"> Chulaimbo Boys Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.chungarimixed.sc.ke \"> Chungari Mixed Day Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.dagorettihigh.sc.ke\"> Dagoretti High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.dandoragirls.sc.ke\"> Dandora Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.dundorisecondary.sc.ke\"> Dundori Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.dzitsonisecondary.com\"> Dzitsoni Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.eastleighhigh.sc.ke\"> Eastleigh High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.eburruschool.sc.ke\"> Eburru Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.elburgondebsecondary.sc.ke\"> Elburgon Deb Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.elburgonsecondary.sc.ke\"> Elburgon Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.emiviasecondary.sc.ke\"> Emivia Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.esibilasecondary.com\"> Esibila Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.flamingosecondary.sc.ke\"> Flamingo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.forestalsecondary.sc.ke\"> Forestal Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.fpfkkayaacademy.com\"> FPFK Kaya Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.freretownsecondary.sc.ke\"> Frere Town Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.friendsschoolkongoni.sc.ke//\"> Friends Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gakuyumahigasecondary.sc.ke\"> Gakuyu Mahiga Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gatunduinisec.sc.ke\"> Gatundu-Ini Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gelegelegirls.sc.ke\"> Gelegele Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gilgildaysecondary.sc.ke\"> Gilgil Day Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gilgilgarrisondaysecondary.sc.ke\"> Gilgil Garrison Day Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gilgiltownsecondary.sc.ke\"> Gilgil Town Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.githungurihigh.sc.ke\"> Githunguri High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.godoloosec.ac.ke\"> God-Oloo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.gotkacholasecondary.sc.ke  \"> Got Kachola Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.hakatisecondary.sc.ke\"> Hakati Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.hassanjohogirls.sc.ke\"> Hassan Joho Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.hekimagirlshigh.sc.ke\"> Hekima Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.hemasecondaryschool-chitago.sc.ke\"> Hema Secondary School – Chitago </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.heroeshigh.sc.ke\"> Heroes High School - Bahati </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.highway.sc.ke\"> Highway Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.holytrinityboyskitale.sc.ke\"> Holy Trinity Boys High School – Kitale </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.honjohnnjorogesecondary.sc.ke\"> Hon. John Njoroge Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.hospitalhillhigh.sc.ke\"> Hospital Hill High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ichichisec.sc.ke\"> Ichichi Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ihigasec.sc.ke\"> Ihiga Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ithangasecondary.com\"> Ithanga Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jmkariukimemsecsch.sc.ke\"> J.M Kariuki Memorial Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jamhurihigh.sc.ke\">Jamhuri High School  </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jehovajiresecondary.sc.ke\"> Jehova Jire Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jomokenyattagirls.sc.ke\"> Jomo Kenyatta Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.jomokenyattahigh.sc.ke\"> Jomo Kenyatta High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kaagagirls.sc.ke\"> Kaaga Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kabaregirls.ac.ke\"> Kabare Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kadikagirls.com\"> Kadika Girls Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kagsjoyacademy.com\"> Kags Joy Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kagumohigh.com\"> Kagumo High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kakamegaschool.org\"> Kakamega School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kaluluinisecondary.sc.ke\"> Kaluluini Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kambaagirlshigh.com\"> Kambaa Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kapkesosiohigh.com\"> Kapkesosio Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.karencsecondary.com\"> Karen C Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.katherigirls.sc.ke\"> Katheri Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thekenyahighschool.com\"> Kenya High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kenyattamahiga.com\"> Kenyatta High School Mahiga </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kenyattahightaita.ac.ke\"> Kenyatta High School Taita </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamainasecondarykirinyaga.sc.ke\"> Kiamaina Secondary Kirinyaga </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamainasecondary.sc.ke\"> Kiamaina Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamainasecondarykerugoya.sc.ke\"> Kiamaina Secondary School Kerugoya </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamanisec.ac.ke\"> Kiamani Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiamberecomplex.ac.ke\"> Kiambere School Complex </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiambutownshipsec.com\"> Kiambu Township Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiberaglorysec.com\"> Kibera Glory Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://kibometsecondary.sc.ke\"> Kibomet Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiburiagirls.com\"> Kiburia Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kijabegirlshigh.com\"> Kijabe Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kilifitownshipsec.com\"> Kilifi Township Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kimaningunjirihigh.sc.ke\"> Kimani Ngunjiri High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kinondosecondary.sc.ke\"> Kinondo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisaunibaptist.com\"> Kisauini Baptist Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisumuboyshigh.com\"> Kisumu Boys High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisumuday.sc.ke\"> Kisumu Day Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kisumugirlshigh.com\"> Kisumu Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kithirunegirls.sc.ke\"> Kithirune Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kiuriverprimary.sc.ke\"> Kiu River Primary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.koelelhigh.sc.ke\"> Koelel High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.komolorumesecondary.sc.ke\"> Komolorume Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.konzaabcsecondary.sc.ke\"> Konza ABC Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kuoyokochiasec.sc.ke\"> Kuoyo Kochia Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kwalehigh.sc.ke\"> Kwale High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kyenigirls.sc.ke\"> Kyeni Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lakelawrenzogirls.sc.ke\"> Lake Lawrenzo Girls </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lambweschool.sc.ke\"> Lambwe Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lamugirls.sc.ke\"> Lamu Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lanetsecondaryschool.sc.ke\"> Lanet Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.langalangasecondary.sc.ke\"> Langa Langa Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.langatahigh.sc.ke\"> Langata High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lemagirlssecondary.ac.ke\"> Lema Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lenanaschool.net\"> Lenana School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://likonimixedsecondary.sc.ke\"> Likoni Mixed Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.loretokiambuhigh.sc.ke\"> Loreto Kiambu Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.luluhigh.sc.ke\"> Lulu High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lusengelisecondary.sc.ke\"> Lusengeli Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.machakosgirls.com\"> Machakos Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mainawanjigisecondary.sc.ke\"> Maina Wanjigi Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.manguhigh.com\"> Mang’u High </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mangu.sc.ke\"> Mangu High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.manguhigh.sc.ke\"> Mangu High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.marshillhigh.sc.ke\"> Mars Hill High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.maryleakeyhighschool.sc.ke\"> Mary Leakey Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.marymountsec.com\"> Mary Mount Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.maryhillgirls.ac.ke\"> Maryhill Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.masenoschool.sc.ke\"> Maseno School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.masiiboys.ac.ke\"> Masii Boys High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mawegogirls.com\"> Mawego Girls Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mbaanisecondary.ac.ke\"> Mbaani Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.menengaihigh.sc.ke\"> Menengai High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mikeusecondary.sc.ke\"> Mikeu Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mnazimojahigh.sc.ke\"> Mnazi Moja High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moiforcesacad.com\"> Moi Forces Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moigesusuhighschool.com\"> Moi Gesusu High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moigirlsmarsabit.sc.ke\"> Moi Girls Marsabit </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moihighmbiruri.sc.ke\"> Moi High Mbiruri </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.moinyatikeboys.sc.ke\"> Moi Nyatike Boys Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mtopangasecondary.sc.ke\"> Mtopanga Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.muhurimuchirihigh.sc.ke\"> Muhuri Muchiri High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.murraygirlstaita.com\"> Murray Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.murugurugirls.com\"> Muruguru Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.musinguhigh.com\"> Musingu High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.muvutiboyshigh.sc.ke\"> Muvuti Boys High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.muyeyehigh.sc.ke\"> Muyeye High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwaanigirls.com\"> Mwaani Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwakitausecondary.sc.ke\"> Mwakitau Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwarikisecondary.sc.ke\"> Mwariki Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwatatesecondary.ac.ke\"> Mwatate Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwikisecondary.sc.ke\"> Mwiki Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mwirutisecondary.sc.ke\"> Mwiruti Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.mzwanenyisecondary.ac.ke\"> Mzwanenyi Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nairobimilimani.sc.ke\"> Nairobi Milimani Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nakuruday.sc.ke\"> Nakuru Day Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nakurugirls.sc.ke\"> Nakuru Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nakuruwestsecondary.sc.ke\"> Nakuru West Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.namawangagirls.sc.ke\"> Namwanga Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.newpalmsecondary.sc.ke\"> New Palm Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ngaragirls.org\"> Ngara Girls School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ngozigirlshigh.sc.ke\"> Ngozi Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nguguinisecondary.sc.ke\"> Nguguini Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ngungurusecondary.sc.ke\"> Ngunguru Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.njorocentralsecondary.sc.ke\"> Njoro Central Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nthongonisecondary.sc.ke\"> Nthongoni Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyagwethesecondary.ac.ke\"> Nyagwethe Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyakiambigirls.sc.ke\"> Nyakiambi Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyanturagohighschool.ac.ke\"> Nyanturago High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyerihigh.com\"> Nyeri High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.nyssecondary.sc.ke\"> NYS Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ofafajerichohigh.sc.ke\"> Ofafa Jericho High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ogongoschool.sc.ke\"> Ogongo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.olmgss-shaurimoyo.sc.ke\"> OLM Girls Secondary School - Shauri Moyo </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ongalosec.com\"> Ongalo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ongalosecondary.sc.ke\"> Ongalo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ongataroyalacademy.sc.ke\"> Ongata Royal Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.orerohigh.sc.ke\"> Orero High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.parklandsschool.com\"> Parklands Boys Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pceaelburgonsecondary.sc.ke\"> PCEA Elburgon Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.preciousbloodkagwegirls.sc.ke\"> Precious Blood Kagwe Girl’s Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.preciousbloodriruta.com\"> Precious Blood Riruta </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.pwanisecondary.sc.ke\"> Pwani Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.rariedadeo.or.ke\"> Rarieda D.E.O </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.rigomagirlshigh.sc.ke\"> Rigoma Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ruaigirls.sc.ke\"> Ruai Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sacredheartmombasa.sc.ke\"> Sacred Heart High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sagegimixed.sc.ke\"> Sagegi Mixed Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.scmwangekasec.com\"> Senior Chief Mwangeka Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.shimolatewaschool.ac.ke\"> Shimo La Tewa High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sigoticomplexgirls.sc.ke\"> Sigoti Girls Complex </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sokorogirls.sc.ke\"> Sokoro Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.sositgirls.sc.ke\"> Sosit Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stpaulskevote.sc.ke\"> St Pauls High School Kevote </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stteresasgirls.sc.ke\"> St Teresas Girls Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.staghansacademy.sc.ke\"> St. Aghans Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stagnesgirlskiranja.sc.ke\"> St. Agnes Kiranja Girls School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stannesisibania.com\"> St. Annes Isibania Girls </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stanthonyengoshura.sc.ke\"> St. Anthony Engoshura </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stbrigidsgirlshigh.com\"> St. Brigid’s Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stfranciswaigiri.sc.ke\"> St. Francis Waigiri Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stgonza.sc.ke\"> St. Gonzaga Gonza Isoge Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjosephkerugoya.sc.ke\"> St. Joseph Kerugoya Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjosephkirima.sc.ke\"> St. Joseph Kirima Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjosephnyabondo.sc.ke\"> St. Joseph Nyabondo Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjosephsboyshigh.sc.ke\"> St. Joseph’s Boys High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjosephsgirls.ac.ke\"> St. Joseph’s Girls Kitale </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stlucykalimani.sc.ke\"> St. Lucy Kalimani Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stmarksboyscherangani.sc.ke\"> St. Marks Boys Cherangani </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.kwaleseminary.com\"> St. Marys Junior Seminary Kwale </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.lwakgirlshigh.ac.ke\"> St. Marys Lwak Girls School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stpetersrambula.sc.ke\"> St. Peter’s Rambula Secondary </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stpetersmumias.sc.ke\"> St. Peters Mumias </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stteresasboys.com\"> St. Teresas Boys Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thomasaquinashigh.sc.ke\"> St. Thomas Aquinas High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stursulagirlstungutu.ac.ke\"> St. Ursula Girls Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://stdeborahgirls.sc.ke\"> St.Deborah Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stcecilianamenya.sc.ke\"> St.Cecilia Sec School Namenya Girls </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stjosephsmtetu.sc.ke\"> St.Josephs Secondary School-Mtetu </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stlukeskhabukoshe.sc.ke\"> St.Lukes Khabukoshe Sec School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://stlukesyattasecondary.sc.ke\"> St.Lukes Yatta Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://stmarksacademy.sc.ke\"> St.Marks Academy </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.stmaryshighlushangonyi.sc.ke\"> St.Marys High School Lushangonyi </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.statehousegirls.org\"> Statehouse Girls School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ladyanndelamere.sc.ke\"> The Lady Ann Delamere Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.rockkongowea.com\"> The Rock Kongowea School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thikahigh.com\"> Thika High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thurdibuoromixed.sc.ke\"> Thurdibuoro Mixed Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.thurdibuoroschool.ac.ke\"> Thurdibuoro Scondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.uthirugirlshigh.com\"> Uthiru Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.ulilinzisecondary.sc.ke\"> Ulilinzi Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.voisecondary.sc.ke\"> Voi Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.vyulyagirls.com\"> Vyulya Girls Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.waagirls.com\"> Waa Girls High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://waberiboysday.sc.ke\"> Waberi Boys Day Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.watuhasec.sc.ke \"> Watuha Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.with\secondary.sc.ke\">Withur Secondary School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.workershighschool.sc.ke\"> Workers High School </a></li>\n";
print "				<li class=\"links\"><a href=\"https://www.xaverian.sc.ke\"> Xaverian Secondary School </a></li>\n";
print "\n";
print "\n";
print "				\n";
print "				</div>\n";
print "	<!-- Services -->\n";
print "\n";
print "	<div class=\"services page_section\">\n";
print "		\n";
print "\n";
print "	</div>\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "</div>\n";
print "\n";
print "<script src=\"js/jquery-3.2.1.min.js\"></script>\n";
print "<script src=\"styles/bootstrap4/popper.js\"></script>\n";
print "<script src=\"styles/bootstrap4/bootstrap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TweenMax.min.js\"></script>\n";
print "<script src=\"plugins/greensock/TimelineMax.min.js\"></script>\n";
print "<script src=\"plugins/scrollmagic/ScrollMagic.min.js\"></script>\n";
print "<script src=\"plugins/greensock/animation.gsap.min.js\"></script>\n";
print "<script src=\"plugins/greensock/ScrollToPlugin.min.js\"></script>\n";
print "<script src=\"plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n";
print "<script src=\"plugins/scrollTo/jquery.scrollTo.min.js\"></script>\n";
print "<script src=\"plugins/easing/easing.js\"></script>\n";
print "<script src=\"js/custom.js\"></script>\n";
print "\n";
print "</body>\n";
print "</html>";

?>
